sudo: required
services:
  - docker

before_install:
  - docker build -t ismaaa/multi-docker -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run ismaaa/multi-docker npm run test -- --coverage

after_success:
  - docker build -t ismaaa/multi-frontend ./frontend
  - docker build -t ismaaa/multi-backend ./backend
  - docker build -t ismaaa/multi-nginx ./nginx
  - docker build -t ismaaa/multi-worker ./worker
  # Log in to the docker CLI
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ismaaa/multi-frontend
  - docker push ismaaa/multi-backend
  - docker push ismaaa/multi-nginx
  - docker push ismaaa/multi-worker

